stages:
  - docker_build
  - docker_deploy

variables:
  CI_REGISTRY_USER: muradsamadov
  CI_REGISTRY_PASSWORD: Docker123!
  IMAGE_TAG: muradsamadov/tomcat-gitlab-runner
  # CI_REGISTRY: https://index.docker.io/v1/


docker_build:
  image: docker:latest
  services:
    - docker:dind
  stage: docker_build
  environment:
    name: docker-build-stage
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker images
    # - docker push $IMAGE_TAG

docker_deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: docker_deploy
  environment:
    name: docker-deploy-stage
    url: http://192.168.52.245:8888/samplewebapp/index.html
  script:
    - docker run -d --name tomcat -p 8888:8080 $IMAGE_TAG
    - echo 'APP deployed'