stages:  # gitlabda deploy prosesinde istifade olunan ardicilliqla icra olunan stages-lerdir.
  - build  # yeniki build birinci icra olunsun, ardicilliq nedirse elede icra olunacaqdir
  - test
  - deploy

pre-job:  # default olaraq .pre stage birinci , en asagida qeyd olunan .post stage-i ise en sonuncu olaraq icra olunacaqdir. Yuxarida qeyd olunan stages hissesinde ise .pre ve .post yazilmir cunki default olaraq birinci ve sonuncu qeyd olunur
  stage: .pre
  script:
    - echo 'This message is from .pre-job'

build-job:
  stage: build
  script:
    - echo 'This message is from build-job'

test-job:
  stage: test
  script:
    - echo 'This message is from test-job'

test-job-2:
  stage: test
  script:
    - echo 'This message is from test-job-2'

deploy-job:
  stage: deploy
  script:
    - echo 'This message is from deploy-job'

post-job:
  stage: .post
  script:
    - echo 'This message is from .post-job'